name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greetings
        run: |
          echo "hi"
          echo "User checking output"
      - name: Print another line
        run: echo "Have a great day!"
